version: "3.3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: chaletSmart2
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - "db:db"

volumes:
  pgadmin-data: