micronaut:
  application:
    name: parkinglot

datasources:
  default:
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    password: ${DB_PASSWORD}
    schema-generate: CREATE_DROP
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}

jpa:
  default:
    compile-time-hibernate-proxies: true
    entity-scan:
      packages: 'com.parkinglot.infra.database.postgresql.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true